### ISSUE TITLE
为什么这个包里什么东西都有？

### ISSUE THREAD

**Issue by JacksonWuxs** [jtyoui/Jtyoui#13]

**Comment by jtyoui** [comment]
这是一个集合包。平时常用的函数，频率用的函数，就抽象封装起来，不是单纯的完成一件事情的项目。这个一个横向项目。

**Comment by jtyoui** [comment]
> _No description provided._

这是一个集合包。平时常用的函数，频率用的函数，就抽象封装起来，不是单纯的完成一件事情的项目。这个一个横向项目。

**Comment by JacksonWuxs** [comment]
感觉只是把自己写代码的一些练习收集了起来，缺乏一些合理的接口和模块关系的设计。
