### ISSUE TITLE
您好，方便说一下码云上分享的搜狗词库表中搜狗分类数据集的压缩密码码

### ISSUE THREAD

**Issue by chendengshuai** [jtyoui/Jtyoui#15]

**Comment by jtyoui** [comment]
> _No description provided._

是这个链接下的吗：https://gitee.com/tyoui/word/tree/master/%E8%AF%8D%E5%BA%93 。你试一下：828530密码，如果不行的话，你可以使用这个方法：https://github.com/jtyoui/Jtyoui/tree/master/jtyoui/sogou
