### ISSUE TITLE
验证码识别

### ISSUE THREAD

**Issue by githubreer** [jtyoui/Jtyoui#16]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.yundama.com', port=80): Max retries exceeded with url: /api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148AF16E4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

api.yundama.com都ping不通...

**Comment by jtyoui** [comment]
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.yundama.com', port=80): Max retries exceeded with url: /api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148AF16E4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
> 
> api.yundama.com都ping不通...

这个是以前调云打码平台的接口，很久没有用了，估计是我充的钱用完了吧

**Comment by githubreer** [comment]
[掩面而泣] 、感谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jtyoui/Jtyoui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午4:21
收件人:&nbsp;"jtyoui/Jtyoui"<Jtyoui@noreply.github.com&gt;;
抄送:&nbsp;"Reer"<1101585768@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jtyoui/Jtyoui] 验证码识别 (#16)





  
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.yundama.com', port=80): Max retries exceeded with url: /api.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000148AF16E4C0&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
 
api.yundama.com都ping不通...
  
这个是以前调云打码平台的接口，很久没有用了，估计是我充的钱用完了吧
