### ISSUE TITLE
Python3.7标准库 | Jtyoui个人微博

### ISSUE THREAD

**Issue by jtyoui** [jtyoui/Jtyoui#9]
https://blog.jtyoui.com/2019/04/03/builtins/ 

 Python3.7标准库下的内置函数使用方法[abs, all, any, ascii, bin, bool, breakpoint, bytearray, bytes, callable, chr, classmethod, compile, complex, copyright,  credits, delattr, dict, dir, divmod, enumerate, eval, ex

**Comment by MacXing** [comment]
666

**Comment by jtyoui** [comment]
> @MacXing
> 666

111
